services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks: [mediabox_net]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Detroit}
    volumes:
      - config:/config/prowlarr
    ports:
      - "9696:9696"
    restart: unless-stopped
