services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks: [mediabox_net]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Detroit}
    volumes:
      - config:/config/sonarr
      - downloads:/downloads
      - media:/media
    ports:
      - "8989:8989"
    restart: unless-stopped
